# Generated by Django 3.2.7 on 2021-10-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accountoperation_operation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountoperation',
            name='operation_dt',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
